// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents an audio file to be treated as music by the Telegram clients.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#audio>

public final class Audio: Codable {
    
    enum CodingKeys: String, CodingKey {
        case fileId = "file_id"
        case duration = "duration"
        case performer = "performer"
        case title = "title"
        case mimeType = "mime_type"
        case fileSize = "file_size"
    }

    public var fileId: String
    public var duration: Int
    public var performer: String?
    public var title: String?
    public var mimeType: String?
    public var fileSize: Int?

    public init (fileId: String, duration: Int, performer: String? = nil, title: String? = nil, mimeType: String? = nil, fileSize: Int? = nil) {
        self.fileId = fileId
        self.duration = duration
        self.performer = performer
        self.title = title
        self.mimeType = mimeType
        self.fileSize = fileSize
    }

}

