// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents a general file (as opposed to photos, voice messages and audio files).
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#document>

public final class Document: Codable {
    
    enum CodingKeys: String, CodingKey {
        case fileId = "file_id"
        case thumb = "thumb"
        case fileName = "file_name"
        case mimeType = "mime_type"
        case fileSize = "file_size"
    }

    public var fileId: String
    public var thumb: PhotoSize?
    public var fileName: String?
    public var mimeType: String?
    public var fileSize: Int?

    public init (fileId: String, thumb: PhotoSize? = nil, fileName: String? = nil, mimeType: String? = nil, fileSize: Int? = nil) {
        self.fileId = fileId
        self.thumb = thumb
        self.fileName = fileName
        self.mimeType = mimeType
        self.fileSize = fileSize
    }

}

