// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents one row of the high scores table for a game.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#gamehighscore>

public final class GameHighScore: Codable {
    
    enum CodingKeys: String, CodingKey {
        case position = "position"
        case user = "user"
        case score = "score"
    }

    public var position: Int
    public var user: User
    public var score: Int

    public init (position: Int, user: User, score: Int) {
        self.position = position
        self.user = user
        self.score = score
    }

}

