// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object contains basic information about an invoice.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#invoice>

public final class Invoice: Codable {
    
    enum CodingKeys: String, CodingKey {
        case title = "title"
        case description = "description"
        case startParameter = "start_parameter"
        case currency = "currency"
        case totalAmount = "total_amount"
    }

    public var title: String
    public var description: String
    public var startParameter: String
    public var currency: String
    public var totalAmount: Int

    public init (title: String, description: String, startParameter: String, currency: String, totalAmount: Int) {
        self.title = title
        self.description = description
        self.startParameter = startParameter
        self.currency = currency
        self.totalAmount = totalAmount
    }

}

