// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents one button of the reply keyboard. For simple text buttons String can be used instead of this object to specify text of the button. Optional fields are mutually exclusive.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#keyboardbutton>

public final class KeyboardButton: Codable {
    
    enum CodingKeys: String, CodingKey {
        case text = "text"
        case requestContact = "request_contact"
        case requestLocation = "request_location"
    }

    public var text: String
    public var requestContact: Bool?
    public var requestLocation: Bool?

    public init (text: String, requestContact: Bool? = nil, requestLocation: Bool? = nil) {
        self.text = text
        self.requestContact = requestContact
        self.requestLocation = requestLocation
    }

}

