// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object contains information about an incoming pre-checkout query.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#precheckoutquery>

public final class PreCheckoutQuery: Codable {
    
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case from = "from"
        case currency = "currency"
        case totalAmount = "total_amount"
        case invoicePayload = "invoice_payload"
        case shippingOptionId = "shipping_option_id"
        case orderInfo = "order_info"
    }

    public var id: String
    public var from: User
    public var currency: String
    public var totalAmount: Int
    public var invoicePayload: String
    public var shippingOptionId: String?
    public var orderInfo: OrderInfo?

    public init (id: String, from: User, currency: String, totalAmount: Int, invoicePayload: String, shippingOptionId: String? = nil, orderInfo: OrderInfo? = nil) {
        self.id = id
        self.from = from
        self.currency = currency
        self.totalAmount = totalAmount
        self.invoicePayload = invoicePayload
        self.shippingOptionId = shippingOptionId
        self.orderInfo = orderInfo
    }

}

