// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// Upon receiving a message with this object, Telegram clients will remove the current custom keyboard and display the default letter-keyboard. By default, custom keyboards are displayed until a new keyboard is sent by a bot. An exception is made for one-time keyboards that are hidden immediately after the user presses a button (see ReplyKeyboardMarkup).
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#replykeyboardremove>

public final class ReplyKeyboardRemove: Codable {
    
    enum CodingKeys: String, CodingKey {
        case removeKeyboard = "remove_keyboard"
        case selective = "selective"
    }

    public var removeKeyboard: Bool = true
    public var selective: Bool?

    public init (removeKeyboard: Bool = true, selective: Bool? = nil) {
        self.removeKeyboard = removeKeyboard
        self.selective = selective
    }

}

