// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents an incoming update.
/// At most one of the optional parameters can be present in any given update.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#update>

public final class Update: Codable {
    
    enum CodingKeys: String, CodingKey {
        case updateId = "update_id"
        case message = "message"
        case editedMessage = "edited_message"
        case channelPost = "channel_post"
        case editedChannelPost = "edited_channel_post"
        case inlineQuery = "inline_query"
        case chosenInlineResult = "chosen_inline_result"
        case callbackQuery = "callback_query"
        case shippingQuery = "shipping_query"
        case preCheckoutQuery = "pre_checkout_query"
    }

    public var updateId: Int
    public var message: Message?
    public var editedMessage: Message?
    public var channelPost: Message?
    public var editedChannelPost: Message?
    public var inlineQuery: InlineQuery?
    public var chosenInlineResult: ChosenInlineResult?
    public var callbackQuery: CallbackQuery?
    public var shippingQuery: ShippingQuery?
    public var preCheckoutQuery: PreCheckoutQuery?

    public init (updateId: Int, message: Message? = nil, editedMessage: Message? = nil, channelPost: Message? = nil, editedChannelPost: Message? = nil, inlineQuery: InlineQuery? = nil, chosenInlineResult: ChosenInlineResult? = nil, callbackQuery: CallbackQuery? = nil, shippingQuery: ShippingQuery? = nil, preCheckoutQuery: PreCheckoutQuery? = nil) {
        self.updateId = updateId
        self.message = message
        self.editedMessage = editedMessage
        self.channelPost = channelPost
        self.editedChannelPost = editedChannelPost
        self.inlineQuery = inlineQuery
        self.chosenInlineResult = chosenInlineResult
        self.callbackQuery = callbackQuery
        self.shippingQuery = shippingQuery
        self.preCheckoutQuery = preCheckoutQuery
    }

}

