// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents a venue.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#venue>

public final class Venue: Codable {
    
    enum CodingKeys: String, CodingKey {
        case location = "location"
        case title = "title"
        case address = "address"
        case foursquareId = "foursquare_id"
    }

    public var location: Location
    public var title: String
    public var address: String
    public var foursquareId: String?

    public init (location: Location, title: String, address: String, foursquareId: String? = nil) {
        self.location = location
        self.title = title
        self.address = address
        self.foursquareId = foursquareId
    }

}

