// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents a video message (available in Telegram apps as of v.4.0).
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#videonote>

public final class VideoNote: Codable {
    
    enum CodingKeys: String, CodingKey {
        case fileId = "file_id"
        case length = "length"
        case duration = "duration"
        case thumb = "thumb"
        case fileSize = "file_size"
    }

    public var fileId: String
    public var length: Int
    public var duration: Int
    public var thumb: PhotoSize?
    public var fileSize: Int?

    public init (fileId: String, length: Int, duration: Int, thumb: PhotoSize? = nil, fileSize: Int? = nil) {
        self.fileId = fileId
        self.length = length
        self.duration = duration
        self.thumb = thumb
        self.fileSize = fileSize
    }

}

