// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents a voice note.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#voice>

public final class Voice: Codable {
    
    enum CodingKeys: String, CodingKey {
        case fileId = "file_id"
        case duration = "duration"
        case mimeType = "mime_type"
        case fileSize = "file_size"
    }

    public var fileId: String
    public var duration: Int
    public var mimeType: String?
    public var fileSize: Int?

    public init (fileId: String, duration: Int, mimeType: String? = nil, fileSize: Int? = nil) {
        self.fileId = fileId
        self.duration = duration
        self.mimeType = mimeType
        self.fileSize = fileSize
    }

}

