// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// Contains information about the current status of a webhook.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#webhookinfo>

public final class WebhookInfo: Codable {
    
    enum CodingKeys: String, CodingKey {
        case url = "url"
        case hasCustomCertificate = "has_custom_certificate"
        case pendingUpdateCount = "pending_update_count"
        case lastErrorDate = "last_error_date"
        case lastErrorMessage = "last_error_message"
        case maxConnections = "max_connections"
        case allowedUpdates = "allowed_updates"
    }

    public var url: String
    public var hasCustomCertificate: Bool
    public var pendingUpdateCount: Int
    public var lastErrorDate: Int?
    public var lastErrorMessage: String?
    public var maxConnections: Int?
    public var allowedUpdates: [String]?

    public init (url: String, hasCustomCertificate: Bool, pendingUpdateCount: Int, lastErrorDate: Int? = nil, lastErrorMessage: String? = nil, maxConnections: Int? = nil, allowedUpdates: [String]? = nil) {
        self.url = url
        self.hasCustomCertificate = hasCustomCertificate
        self.pendingUpdateCount = pendingUpdateCount
        self.lastErrorDate = lastErrorDate
        self.lastErrorMessage = lastErrorMessage
        self.maxConnections = maxConnections
        self.allowedUpdates = allowedUpdates
    }

}

