// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents an incoming callback query from a callback button in an inline keyboard. If the button that originated the query was attached to a message sent by the bot, the field message will be present. If the button was attached to a message sent via the bot (in inline mode), the field inline_message_id will be present. Exactly one of the fields data or game_short_name will be present.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#callbackquery>

public final class CallbackQuery: Codable {
    
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case from = "from"
        case message = "message"
        case inlineMessageId = "inline_message_id"
        case chatInstance = "chat_instance"
        case data = "data"
        case gameShortName = "game_short_name"
    }

    public var id: String
    public var from: User
    public var message: Message?
    public var inlineMessageId: String?
    public var chatInstance: String
    public var data: String?
    public var gameShortName: String?

    public init (id: String, from: User, message: Message? = nil, inlineMessageId: String? = nil, chatInstance: String, data: String? = nil, gameShortName: String? = nil) {
        self.id = id
        self.from = from
        self.message = message
        self.inlineMessageId = inlineMessageId
        self.chatInstance = chatInstance
        self.data = data
        self.gameShortName = gameShortName
    }

}

