// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents a chat.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#chat>

public final class Chat: Codable {
    
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case type = "type"
        case title = "title"
        case username = "username"
        case firstName = "first_name"
        case lastName = "last_name"
        case allMembersAreAdministrators = "all_members_are_administrators"
        case photo = "photo"
        case description = "description"
        case inviteLink = "invite_link"
        case pinnedMessage = "pinned_message"
        case stickerSetName = "sticker_set_name"
        case canSetStickerSet = "can_set_sticker_set"
    }

    public var id: Int64
    public var type: String
    public var title: String?
    public var username: String?
    public var firstName: String?
    public var lastName: String?
    public var allMembersAreAdministrators: Bool?
    public var photo: ChatPhoto?
    public var description: String?
    public var inviteLink: String?
    public var pinnedMessage: Message?
    public var stickerSetName: String?
    public var canSetStickerSet: Bool?

    public init (id: Int64, type: String, title: String? = nil, username: String? = nil, firstName: String? = nil, lastName: String? = nil, allMembersAreAdministrators: Bool? = nil, photo: ChatPhoto? = nil, description: String? = nil, inviteLink: String? = nil, pinnedMessage: Message? = nil, stickerSetName: String? = nil, canSetStickerSet: Bool? = nil) {
        self.id = id
        self.type = type
        self.title = title
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.allMembersAreAdministrators = allMembersAreAdministrators
        self.photo = photo
        self.description = description
        self.inviteLink = inviteLink
        self.pinnedMessage = pinnedMessage
        self.stickerSetName = stickerSetName
        self.canSetStickerSet = canSetStickerSet
    }

}

