// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents one button of an inline keyboard. You must use exactly one of the optional fields.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#inlinekeyboardbutton>

public final class InlineKeyboardButton: Codable {
    
    enum CodingKeys: String, CodingKey {
        case text = "text"
        case url = "url"
        case callbackData = "callback_data"
        case switchInlineQuery = "switch_inline_query"
        case switchInlineQueryCurrentChat = "switch_inline_query_current_chat"
        case callbackGame = "callback_game"
        case pay = "pay"
    }

    public var text: String
    public var url: String?
    public var callbackData: String?
    public var switchInlineQuery: String?
    public var switchInlineQueryCurrentChat: String?
    public var callbackGame: CallbackGame?
    public var pay: Bool?

    public init (text: String, url: String? = nil, callbackData: String? = nil, switchInlineQuery: String? = nil, switchInlineQueryCurrentChat: String? = nil, callbackGame: CallbackGame? = nil, pay: Bool? = nil) {
        self.text = text
        self.url = url
        self.callbackData = callbackData
        self.switchInlineQuery = switchInlineQuery
        self.switchInlineQueryCurrentChat = switchInlineQueryCurrentChat
        self.callbackGame = callbackGame
        self.pay = pay
    }

}

