// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents an inline keyboard that appears right next to the message it belongs to.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#inlinekeyboardmarkup>

public final class InlineKeyboardMarkup: Codable {
    
    enum CodingKeys: String, CodingKey {
        case inlineKeyboard = "inline_keyboard"
    }

    public var inlineKeyboard: [[InlineKeyboardButton]]

    public init (inlineKeyboard: [[InlineKeyboardButton]]) {
        self.inlineKeyboard = inlineKeyboard
    }

}

