// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// Represents the content of a contact message to be sent as the result of an inline query.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#inputcontactmessagecontent>

public final class InputContactMessageContent: Codable {
    
    enum CodingKeys: String, CodingKey {
        case phoneNumber = "phone_number"
        case firstName = "first_name"
        case lastName = "last_name"
    }

    public var phoneNumber: String
    public var firstName: String
    public var lastName: String?

    public init (phoneNumber: String, firstName: String, lastName: String? = nil) {
        self.phoneNumber = phoneNumber
        self.firstName = firstName
        self.lastName = lastName
    }

}

