// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents the content of a media message to be sent. It should be one of
/// InputMediaPhoto
/// InputMediaVideo
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#inputmedia>

public final class InputMedia: Codable {
    
    enum CodingKeys: String, CodingKey {
    }


    public init () {
    }

}

