// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/// This object represents one special entity in a text message. For example, hashtags, usernames, URLs, etc.
///
/// [- SeeAlso: ]<https://core.telegram.org/bots/api#messageentity>

public final class MessageEntity: Codable {
    
    enum CodingKeys: String, CodingKey {
        case type = "type"
        case offset = "offset"
        case length = "length"
        case url = "url"
        case user = "user"
    }

    public var type: String
    public var offset: Int
    public var length: Int
    public var url: String?
    public var user: User?

    public init (type: String, offset: Int, length: Int, url: String? = nil, user: User? = nil) {
        self.type = type
        self.offset = offset
        self.length = length
        self.url = url
        self.user = user
    }

}

