// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.


import HTTP

public extension Bot {

    /**
     A simple method for testing your bot's auth token. Requires no parameters. Returns basic information about the bot in form of a User object.

     SeeAlso Telegram Bot API Reference:
     [GetMeParams](https://core.telegram.org/bots/api#getme)
     
     - Parameters:
         - params: Parameters container, see `GetMeParams` struct
     - Throws: Throws on errors
     - Returns: Future of `User` type
     */
    @discardableResult
    func getMe() throws -> Future<User> {
        let response: Future<TelegramContainer<User>>
        response = try client.respond(endpoint: "getMe", body: HTTPBody(), headers: HTTPHeaders())
        return response.flatMap(to: User.self) { try self.wrap($0) }
    }
}
