// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

public extension Bot {

    /// Parameters container struct for `getStickerSet` method
    struct GetStickerSetParams: JSONEncodable {

        /// Name of the sticker set
        var name: String

        /// Custom keys for coding/decoding `GetStickerSetParams` struct
        enum CodingKeys: String, CodingKey {
            case name = "name"
        }

        public init(name: String) {
            self.name = name
        }
    }

    /**
     Use this method to get a sticker set. On success, a StickerSet object is returned.

     SeeAlso Telegram Bot API Reference:
     [GetStickerSetParams](https://core.telegram.org/bots/api#getstickerset)
     
     - Parameters:
         - params: Parameters container, see `GetStickerSetParams` struct
     - Throws: Throws on errors
     - Returns: Future of `StickerSet` type
     */
    @discardableResult
    func getStickerSet(params: GetStickerSetParams) throws -> Future<StickerSet> {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "getStickerSet", body: body, headers: headers)
            .flatMapThrowing { (container) -> StickerSet in
                return try self.processContainer(container)
        }
    }
}

// MARK: Concurrency Support
#if compiler(>=5.5)
@available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)
public extension Bot {

    /**
     Use this method to get a sticker set. On success, a StickerSet object is returned.

     SeeAlso Telegram Bot API Reference:
     [GetStickerSetParams](https://core.telegram.org/bots/api#getstickerset)
     
     - Parameters:
         - params: Parameters container, see `GetStickerSetParams` struct
     - Throws: Throws on errors
     - Returns: Future of `StickerSet` type
     */
    @discardableResult
    func getStickerSet(params: GetStickerSetParams) async throws -> StickerSet {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try self.processContainer(try await client.request(endpoint: "getStickerSet", body: body, headers: headers))
    }
}
#endif
