// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

public extension Bot {

    /// Parameters container struct for `createChatInviteLink` method
    struct CreateChatInviteLinkParams: JSONEncodable {

        /// Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        var chatId: ChatId

        /// Point in time (Unix timestamp) when the link will expire
        var expireDate: Int?

        /// Maximum number of users that can be members of the chat simultaneously after joining the chat via this invite link; 1-99999
        var memberLimit: Int?

        /// Custom keys for coding/decoding `CreateChatInviteLinkParams` struct
        enum CodingKeys: String, CodingKey {
            case chatId = "chat_id"
            case expireDate = "expire_date"
            case memberLimit = "member_limit"
        }

        public init(chatId: ChatId, expireDate: Int? = nil, memberLimit: Int? = nil) {
            self.chatId = chatId
            self.expireDate = expireDate
            self.memberLimit = memberLimit
        }
    }

    /**
     Use this method to create an additional invite link for a chat. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. The link can be revoked using the method revokeChatInviteLink. Returns the new invite link as ChatInviteLink object.

     SeeAlso Telegram Bot API Reference:
     [CreateChatInviteLinkParams](https://core.telegram.org/bots/api#createchatinvitelink)
     
     - Parameters:
         - params: Parameters container, see `CreateChatInviteLinkParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */
    @discardableResult
    func createChatInviteLink(params: CreateChatInviteLinkParams) throws -> Future<Bool> {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "createChatInviteLink", body: body, headers: headers)
            .flatMapThrowing { (container) -> Bool in
                return try self.processContainer(container)
        }
    }
}

// MARK: Concurrency Support
#if compiler(>=5.5)
@available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)
public extension Bot {

    /**
     Use this method to create an additional invite link for a chat. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. The link can be revoked using the method revokeChatInviteLink. Returns the new invite link as ChatInviteLink object.

     SeeAlso Telegram Bot API Reference:
     [CreateChatInviteLinkParams](https://core.telegram.org/bots/api#createchatinvitelink)
     
     - Parameters:
         - params: Parameters container, see `CreateChatInviteLinkParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */
    @discardableResult
    func createChatInviteLink(params: CreateChatInviteLinkParams) async throws -> Bool {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try self.processContainer(try await client.request(endpoint: "createChatInviteLink", body: body, headers: headers))
    }
}
#endif
