// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

public extension Bot {

    /**
     Use this method to close the bot instance before moving it from one local server to another. You need to delete the webhook before calling this method to ensure that the bot isn't launched again after server restart. The method will return error 429 in the first 10 minutes after the bot is launched. Returns True on success. Requires no parameters.

     SeeAlso Telegram Bot API Reference:
     [CloseParams](https://core.telegram.org/bots/api#close)
     
     - Parameters:
         - params: Parameters container, see `CloseParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */
    @discardableResult
    func close() throws -> Future<Bool> {
        return try client
            .request(endpoint: "close")
            .flatMapThrowing { (container) -> Bool in
                return try self.processContainer(container)
        }
    }
}

// MARK: Concurrency Support
#if compiler(>=5.5)
@available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)
public extension Bot {

    /**
     Use this method to close the bot instance before moving it from one local server to another. You need to delete the webhook before calling this method to ensure that the bot isn't launched again after server restart. The method will return error 429 in the first 10 minutes after the bot is launched. Returns True on success. Requires no parameters.

     SeeAlso Telegram Bot API Reference:
     [CloseParams](https://core.telegram.org/bots/api#close)
     
     - Parameters:
         - params: Parameters container, see `CloseParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */
    @discardableResult
    func close() async throws -> Bool {
        return try self.processContainer(try await client.request(endpoint: "close"))
    }
}
#endif
