// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

public extension Bot {

    /// Parameters container struct for `editChatInviteLink` method
    struct EditChatInviteLinkParams: JSONEncodable {

        /// Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        var chatId: ChatId

        /// The invite link to edit
        var inviteLink: String

        /// Point in time (Unix timestamp) when the link will expire
        var expireDate: Int?

        /// Maximum number of users that can be members of the chat simultaneously after joining the chat via this invite link; 1-99999
        var memberLimit: Int?

        /// Custom keys for coding/decoding `EditChatInviteLinkParams` struct
        enum CodingKeys: String, CodingKey {
            case chatId = "chat_id"
            case inviteLink = "invite_link"
            case expireDate = "expire_date"
            case memberLimit = "member_limit"
        }

        public init(chatId: ChatId, inviteLink: String, expireDate: Int? = nil, memberLimit: Int? = nil) {
            self.chatId = chatId
            self.inviteLink = inviteLink
            self.expireDate = expireDate
            self.memberLimit = memberLimit
        }
    }

    /**
     Use this method to edit a non-primary invite link created by the bot. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns the edited invite link as a ChatInviteLink object.

     SeeAlso Telegram Bot API Reference:
     [EditChatInviteLinkParams](https://core.telegram.org/bots/api#editchatinvitelink)
     
     - Parameters:
         - params: Parameters container, see `EditChatInviteLinkParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */
    @discardableResult
    func editChatInviteLink(params: EditChatInviteLinkParams) throws -> Future<Bool> {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try client
            .request(endpoint: "editChatInviteLink", body: body, headers: headers)
            .flatMapThrowing { (container) -> Bool in
                return try self.processContainer(container)
        }
    }
}

// MARK: Concurrency Support
#if compiler(>=5.5)
@available(macOS 12.0, iOS 15.0, watchOS 8.0, tvOS 15.0, *)
public extension Bot {

    /**
     Use this method to edit a non-primary invite link created by the bot. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Returns the edited invite link as a ChatInviteLink object.

     SeeAlso Telegram Bot API Reference:
     [EditChatInviteLinkParams](https://core.telegram.org/bots/api#editchatinvitelink)
     
     - Parameters:
         - params: Parameters container, see `EditChatInviteLinkParams` struct
     - Throws: Throws on errors
     - Returns: Future of `Bool` type
     */
    @discardableResult
    func editChatInviteLink(params: EditChatInviteLinkParams) async throws -> Bool {
        let body = try httpBody(for: params)
        let headers = httpHeaders(for: params)
        return try self.processContainer(try await client.request(endpoint: "editChatInviteLink", body: body, headers: headers))
    }
}
#endif
