// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/**
 This object represents the scope to which bot commands are applied. Currently, the following 7 scopes are supported:
 BotCommandScopeDefault
 BotCommandScopeAllPrivateChats
 BotCommandScopeAllGroupChats
 BotCommandScopeAllChatAdministrators
 BotCommandScopeChat
 BotCommandScopeChatAdministrators
 BotCommandScopeChatMember

 SeeAlso Telegram Bot API Reference:
 [BotCommandScope](https://core.telegram.org/bots/api#botcommandscope)
 */
public final class BotCommandScope: Codable {

}
