// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/**
 This object contains information about one member of a chat. Currently, the following 6 types of chat members are supported:
 ChatMemberOwner
 ChatMemberAdministrator
 ChatMemberMember
 ChatMemberRestricted
 ChatMemberLeft
 ChatMemberBanned

 SeeAlso Telegram Bot API Reference:
 [ChatMember](https://core.telegram.org/bots/api#chatmember)
 */
public final class ChatMember: Codable {

}
