// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/**
 This object contains information about a poll.

 SeeAlso Telegram Bot API Reference:
 [Poll](https://core.telegram.org/bots/api#poll)
 */
public final class Poll: Codable {

    /// Custom keys for coding/decoding `Poll` struct
    enum CodingKeys: String, CodingKey {
        case id = "id"
        case question = "question"
        case options = "options"
        case isClosed = "is_closed"
    }

    /// Unique poll identifier
    public var id: String

    /// Poll question, 1-255 characters
    public var question: String

    /// List of poll options
    public var options: [PollOption]

    /// True, if the poll is closed
    public var isClosed: Bool

    public init (id: String, question: String, options: [PollOption], isClosed: Bool) {
        self.id = id
        self.question = question
        self.options = options
        self.isClosed = isClosed
    }
}
