// Telegrammer - Telegram Bot Swift SDK.
// This file is autogenerated by API/generate_wrappers.rb script.

/**
 This object represents a service message about a voice chat started in the chat. Currently holds no information.

 SeeAlso Telegram Bot API Reference:
 [VoiceChatStarted](https://core.telegram.org/bots/api#voicechatstarted)
 */
public final class VoiceChatStarted: Codable {

}
